nav:
  - 开篇: 
      - 开始新篇章: index.md
      - 准备工作: guides/preparation.md
      - 服规: rules.md
      - 常见问题解答: guides/FAQs.md
      - 更新记录: update.md
  - 生存:
      - 服务端更改: external/changes.md
      - 新增功能/玩法: external/features.md
      - 已知Bugs: external/known_bugs.md
  - 封神榜: banlist.md
  - 赞助: sponsors.md
  - 友情链接: friendship_link.md
  - 网页地图: https://map.shamizo.top  
  - 图片生成: https://pic.shamizo.top    
